"use client";
import { useEffect, useState } from "react";
export default function UnknownScansPage(){
 const [records,setRecords]=useState<any[]>([]); const [forms,setForms]=useState<Record<string,any>>({}); const [msg,setMsg]=useState("");
 async function load(){const d=await fetch('/api/unknown-scans',{cache:'no-store'}).then(r=>r.json()); setRecords(d.records||[])}
 useEffect(()=>{load()},[]);
 function setField(id:string,k:string,v:any){setForms(p=>({...p,[id]:{...(p[id]||{}),[k]:v}}))}
 async function resolve(id:string, ndc:string){const f=forms[id]||{}; setMsg(''); const res=await fetch('/api/resolve-unknown',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({unknownId:id,ndc,productRecordId:f.productRecordId,currentQuantity:f.currentQuantity||0,location:f.location||'',resolvedBy:f.resolvedBy||''})}); const data=await res.json(); if(!res.ok){setMsg(data.error||'Resolve failed'); return;} setMsg('Resolved successfully'); load();}
 return <main><h1>Unknown Scans</h1><p className="muted">Create/select the Product in Airtable first, then paste that Product record ID here to resolve the NDC into Inventory.</p>{msg&&<div className="card warning">{msg}</div>}{records.map(r=>{const f=r.fields; return <div className="card" key={r.id}><h3>{f.NDC}</h3><p><strong>Raw:</strong> {f['Raw Scan Value']}</p><p><strong>Action/Qty:</strong> {f.Action} {f.Quantity}</p><div className="grid"><div><label>Product Record ID</label><input placeholder="recXXXXXXXXXXXXXX" onChange={e=>setField(r.id,'productRecordId',e.target.value)}/></div><div><label>Starting Current Quantity</label><input type="number" defaultValue={0} onChange={e=>setField(r.id,'currentQuantity',Number(e.target.value))}/></div><div><label>Location</label><input onChange={e=>setField(r.id,'location',e.target.value)}/></div><div><label>Resolved By *</label><input required onChange={e=>setField(r.id,'resolvedBy',e.target.value)}/></div></div><button className="button" onClick={()=>resolve(r.id,f.NDC)}>Resolve to Inventory</button></div>})}{records.length===0&&<div className="card success">No unresolved unknown scans.</div>}</main>
}
